/**
 * extract-obligations — tag obligations across a contract (or the whole
 * markdown corpus) and synthesize one Obligation resource per detected
 * obligation, with structured fields (obligor, obligee, trigger, deadline,
 * source-section reference) generated by yield.fromAnnotation.
 *
 * Usage: tsx skills/extract-obligations/script.ts [<contractResourceId>] [--interactive]
 */

import {
  SemiontClient,
  entityType,
  resourceId as ridBrand,
  type AnnotationId,
  type GatheredContext,
  type ResourceId,
} from '@semiont/sdk';
import { confirm, isInteractive, close as closeInteractive } from '../../src/interactive.js';
import { createdCount } from '../../src/mark-result.js';

const DEFAULT_INSTRUCTIONS = `
Tag every obligation, duty, covenant, restriction, or commitment in this document.
Examples of patterns to tag:
  - "X shall …" / "X must …" / "X agrees to …"  (affirmative duty)
  - "X shall not …" / "without the prior written consent of Y"  (restriction)
  - "X covenants that …"  (covenant)
  - "X represents and warrants that …"  (representation/warranty)
  - "the parties agree that …"  (mutual obligation)
  - survival, indemnification, limitation-of-liability, and assignment clauses
For each tagged span, the *exact text* should be the obligation language itself
(quoting the verb plus its object), not a paraphrase. Skip purely-definitional
language ("'X' means …") and mere references ("see Section 4.2"); those aren't
obligations.
`.trim();

const INSTRUCTIONS = process.env.OBLIGATION_INSTRUCTIONS ?? DEFAULT_INSTRUCTIONS;

function getMediaType(r: any): string | undefined {
  const reps = Array.isArray(r.representations)
    ? r.representations
    : r.representations
      ? [r.representations]
      : [];
  return reps[0]?.mediaType;
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '').slice(0, 80);
}

interface ObligationAnno {
  rId: ResourceId;
  annId: AnnotationId;
  text: string;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2).filter((a) => !a.startsWith('-'));
  const explicitResourceId = args[0];

  const semiont = await SemiontClient.signInHttp({
    baseUrl: process.env.SEMIONT_API_URL ?? 'http://localhost:4000',
    email: process.env.SEMIONT_USER_EMAIL!,
    password: process.env.SEMIONT_USER_PASSWORD!,
  });

  let targets: ResourceId[];
  if (explicitResourceId) {
    targets = [ridBrand(explicitResourceId)];
  } else {
    const all = await semiont.browse.resources({ limit: 1000 });
    targets = all
      .filter((r) => {
        const mt = getMediaType(r);
        return mt === 'text/markdown' || mt === 'text/plain';
      })
      .map((r) => ridBrand(r['@id']));
  }

  if (targets.length === 0) {
    console.log('No markdown corpus resources found.');
    semiont.dispose();
    closeInteractive();
    return;
  }

  console.log(
    `Pass 1: mark.assist (motivation: linking, entityTypes: [Obligation]) ` +
      `against ${targets.length} resource(s).`,
  );
  const proceedMark = await confirm('Proceed?', true);
  if (!proceedMark) {
    console.log('Aborted.');
    semiont.dispose();
    closeInteractive();
    return;
  }

  for (const rId of targets) {
    const progress = await semiont.mark.assist(rId, 'linking', {
      entityTypes: [entityType('Obligation')],
      instructions: INSTRUCTIONS,
    });
    const n = createdCount(progress);
    console.log(`  ${rId}: ${n} obligation annotations`);
  }

  // Pass 2: collect Obligation annotations + synthesize per-obligation resources.
  console.log('\nPass 2: synthesizing Obligation resources...');
  const obligationAnnotations: ObligationAnno[] = [];
  for (const rId of targets) {
    const annotations = await semiont.browse.annotations(rId);
    for (const ann of annotations) {
      if (ann.motivation !== 'linking') continue;
      const bodies = Array.isArray(ann.body) ? ann.body : ann.body ? [ann.body] : [];
      const alreadyBound = bodies.some(
        (b: any) =>
          b.type === 'SpecificResource' && b.purpose === 'linking',
      );
      if (alreadyBound) continue;
      const tags = bodies
        .filter((b: any) => b.type === 'TextualBody' && b.purpose === 'tagging')
        .flatMap((b: any) => (Array.isArray(b.value) ? b.value : [b.value]));
      if (!tags.includes('Obligation')) continue;
      const target = ann.target;
      const selectors =
        typeof target === 'string' || !target.selector
          ? []
          : Array.isArray(target.selector)
            ? target.selector
            : [target.selector];
      let quote = '';
      for (const s of selectors) {
        if (s.type === 'TextQuoteSelector') { quote = s.exact; break; }
      }
      obligationAnnotations.push({
        rId,
        annId: ann.id,
        text: quote,
      });
    }
  }

  if (obligationAnnotations.length === 0) {
    console.log('No unbound Obligation annotations found.');
    semiont.dispose();
    closeInteractive();
    return;
  }

  console.log(
    `Found ${obligationAnnotations.length} unbound Obligation annotation(s). ` +
      `Each will trigger a yield.fromAnnotation call (one LLM completion per obligation).`,
  );
  const proceedYield = await confirm('Proceed?', true);
  if (!proceedYield) {
    console.log('Aborted before synthesis pass.');
    semiont.dispose();
    closeInteractive();
    return;
  }

  let synthesized = 0;
  let skipped = 0;
  for (const a of obligationAnnotations) {
    const proceedOne = isInteractive()
      ? await confirm(`Synthesize Obligation for "${a.text.slice(0, 80)}…"?`, true)
      : true;
    if (!proceedOne) {
      skipped++;
      continue;
    }

    const gather = await semiont.gather.annotation(a.rId, a.annId, { contextWindow: 1500 });
    if (!('response' in gather)) continue;
    const context = gather.response as GatheredContext;

    const yieldEvent = await semiont.yield.fromAnnotation(a.rId, a.annId, {
      title: `Obligation: ${a.text.slice(0, 80)}`,
      storageUri: `file://generated/obligation-${slugify(a.text)}-${Date.now()}.md`,
      context,
      entityTypes: ['Obligation'],
    });
    if (yieldEvent.kind !== 'complete') {
      console.warn(`  unexpected yield event: ${yieldEvent.kind}`);
      continue;
    }
    const newRId = (yieldEvent.data.result as { resourceId?: string } | undefined)?.resourceId;
    if (!newRId) {
      console.warn(`  yield.fromAnnotation gave no resourceId for "${a.text}"`);
      continue;
    }

    await semiont.bind.body(a.rId, a.annId, [
      {
        op: 'add',
        item: { type: 'SpecificResource', source: newRId, purpose: 'linking' },
      },
    ]);
    synthesized++;
    console.log(`  + Obligation: "${a.text.slice(0, 60)}…" → ${newRId}`);
  }

  console.log(`\nDone. Synthesized ${synthesized} Obligation resource(s); ${skipped} skipped.`);
  semiont.dispose();
  closeInteractive();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
